matrix:
    include:
        - language: go
          go: 1.7.x
        - language: go
          go: 1.8.x
        - language: go
          go: 1.9.x
        - language: go
          go: master

    fast_finish: true
    allow_failures:
        - go: master

sudo: false
