matrix:
    include:
        - language: go
          go: 1.7.x
        - language: go
          go: 1.8.x
        - language: go
          go: 1.9.x
        - language: go
          go: master

        - language: python
          python: 2.7
          install: pip install --upgrade ./py-proio
          script: pytest ./py-proio
        - language: python
          python: 3.6
          install: pip install --upgrade ./py-proio
          script: pytest ./py-proio
        - language: python
          python: nightly
          install: pip install --upgrade ./py-proio
          script: pytest ./py-proio

    fast_finish: true
    allow_failures:
        - go: master
        - python: nightly

sudo: false
